version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.4-jdk-stretch
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "5f:0f:56:8a:fb:59:8e:63:b8:4e:5e:e9:52:f1:c1:bc"
      - restore_cache:
          key: v1-gradle-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - run:
          name: build
          command: ./gradlew clean build check
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-gradle-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          when: always
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  deploy:
    docker:
      - image: circleci/openjdk:11.0.4-jdk-stretch
    environment:
      APP_NAME: htbhf-java-common
      BINTRAY_ROOT_URL: https://dl.bintray.com/departmentofhealth-htbhf/maven/uk/gov/dhsc/htbhf
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "5f:0f:56:8a:fb:59:8e:63:b8:4e:5e:e9:52:f1:c1:bc"
      - attach_workspace:
          at: .
      - run:
          name: upload test coverage
          command: ./gradlew jacocoTestReport testReport copyReports && bash <(curl -s https://codecov.io/bash)
      - run:
          name: set TRAVIS_BRANCH as this is required by shipkit
          command: |
            echo "export TRAVIS_BRANCH=$CIRCLE_BRANCH" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: release
          command: ./gradlew -PskipComparePublications=true && ./gradlew ciPerformRelease -s

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
